config/routes.rb
Rails.application.routes.draw do
  devise_for :customers, skip: [:passwords], controllers: {
   registrations: "public/registrations",
   sessions: "public/sessions"
  }

  devise_for :admin, skip: [:registrations, :passwords], controllers: {
   sessions: "admin/sessions"
  }
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html


  devise_scope :customer do
    post "customers/guest_sign_in", to: "public/sessions#guest_sign_in"
  end
  root to: "public/homes#top"


  scope module: :public do
    get "/customers/sign_up" => "registrations#new"
    post "/customers" => "registrations#create"
    get "/customers/mypage" => "customers#show"


    get "search", to: "spots#search"


    resources :spots, only: [:new, :create, :index, :show, :destroy] do
      resource :favorites, only: [:create, :destroy]
      resources :comments
    end
    resources :customers, only: [:show, :edit, :update] do
      get :favorites, on: :collection
    end
  end



  namespace :admin do
    get "search", to: "spots#search"
    get "/admin" => "homes#top"
    # delete '/spots/:id' => 'spots#destroy', as: 'destroy_spot'
    resources :spots
    resources :customers
    resources :genres
    resources :comments, only: :destroy
  end
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_one_attached :image
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :customer
  belongs_to :spot

  validates :rate, numericality: {
   less_than_or_equal_to: 5,
   greater_than_or_equal_to: 1,
 }, presence: true
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :spots, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :favorited_spots, through: :favorites, source: :spot
  has_many :comments, dependent: :destroy
  has_one_attached :image
  validates :name, presence: true
  validates :email, uniqueness: { message: "そのアドレスは使用できません" },
                  confirmation: true

  def self.guest
    find_or_create_by!(email: "guest@example.com") do |customer|
      customer.password = SecureRandom.urlsafe_base64
      customer.name = "ゲスト"
    end
  end

  def mine?(object)
    object.customer_id == id
  end

  def favorite(spot)
    favorites_spots << post
  end

  def unfavorite(spot)
    favorites_spots.destroy(post)
  end

  def favorite?(spot)
    favorites_spots.include?(post)
  end

  def get_image(width, height)
    unless image.attached?
      file_path = Rails.root.join("app/assets/images/no_image.jpg")
      image.attach(io: File.open(file_path), filename: "default-image.jpg", content_type: "image/jpeg")
    end
    image.variant(resize_to_limit: [width, height]).processed
  end
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :customer
  belongs_to :spot

  validates_uniqueness_of :spot_id, scope: :customer_id
end

app/models/genre.rb
class Genre < ApplicationRecord
  validates :genre_name, presence: true

  def self.ransackable_attributes(auth_object = nil)
    ["genre_name"]
  end
end

app/models/helpful.rb
class Helpful < ApplicationRecord
end

app/models/prefecture.rb
class Prefecture < ApplicationRecord
  validates :prefecture_name, presence: true, uniqueness: { case_sensitive: false }

  # belongs_to :spot
end

app/models/spot.rb
class Spot < ApplicationRecord
  has_one_attached :image
  belongs_to :customer, optional: true
  has_many :favorites, dependent: :destroy
  has_many :customers, through: :favorites
  has_many :comments, dependent: :destroy

  #  belongs_to :prefecture
  validates :spot_name, presence: true
  validates :address, presence: true
  validate :access
  validate :telephone_number
  validate :url
  validate :facility
  validate :business_day
  # validates :content, presence: true, length: { maximum: 65_535 }

  def get_image
    unless image.attached?
      file_path = Rails.root.join("app/assets/images/no_image.jpg")
      image.attach(io: File.open(file_path), filename: "default-image.jpg", content_type: "image/jpeg")
    end
    image
  end

  def self.ransackable_attributes(auth_object = nil)
    ["id", "genre_id", "prefectures_id"]
  end

  def self.ransackable_associations(auth_object = nil)
    ["genre", "prefecture"]
  end
end

app/models/user.rb
class User < ApplicationRecord
end

app/controllers/admin/spots_controller.rb
class Admin::SpotsController < ApplicationController
  before_action :authenticate_admin!
  def new
    @spot = Spot.new
  end

  def create
    @spot = Spot.new(spot_params)
    if @spot.save
      redirect_to "/admin/spots"
    else
      render :new, status: :unprocessable_entity
    end
  end

  def index
    @spot = Spot.page(params[:page]).per(10)
    @q = Spot.ransack(params[:q])
    @spots = @q.result(distinct: true).page(params[:page]).per(8)
    @prefectures = Prefecture.all
  end

  def search
    @q = Spot.ransack(search_params)
    @spots = @q.result(distinct: true).page(params[:page]).per(8)
    @prefectures = Prefecture.all
    render :index
  end

  def show
    @spot = Spot.find(params[:id])
  end

  def edit
    @spot = Spot.find(params[:id])
  end

  def destroy
    @spot = Spot.find(params[:id])
    @spot.destroy
    redirect_to "/admin/spots"
  end

  def update
    @spot = Spot.find(params[:id])

    if @spot.update(spot_params)
      flash[:notice] = "You have updated item successfully."
      redirect_to admin_spot_path(@spot.id)
    else
      render "edit"
    end
  end

   private
     def spot_params
       params.require(:spot).permit(:spot_name, :address, :access, :telephone_number, :url, :facility, :business_day, :opening_hours, :image, :genre_id, :prefectures_id)
     end

     def search_params
       params.require(:q).permit!
     end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  def after_sign_out_path_for(resource_or_scope)
    if resource_or_scope == :customer
      root_path
    elsif resource_or_scope == :admin
      new_admin_session_path
    else
      admin_admin_path
    end
  end
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  before_action :set_spot
  before_action :authenticate_customer!
  
  def create
    if @spot.customer_id != current_customer.id
      @favorite = Favorite.create(customer_id: current_customer.id, spot_id: @spot.id)
    end
  end
  
  def destroy
    @favorite = Favorite.find_by(customer_id: current_customer.id, spot_id: @spot.id)
    @favorite.destroy
  end

  private
  def set_spot
    @spot = Spot.find(params[:spot_id])
  end
end

app/controllers/prefectures_controller.rb
class PrefecturesController < ApplicationController
  def index
    @q = Prefecture.ransack
    @prefectures = @q.result(distinct: true)
  end

  def search
    @q = Hoge.ransack(search_params)
    @prefectures = @q.result(distinct: true)
  end

  private
    def search_params
      params.require(:q).permit!
    end
end

app/helpers/admin/comments_helper.rb
module Admin::CommentsHelper
end

app/helpers/admin/go_out_helper.rb
module Admin::GoOutHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/salons_helper.rb
module Admin::SalonsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/genres_helper.rb
module GenresHelper
end

app/helpers/prefectures_helper.rb
module PrefecturesHelper
end

app/helpers/spots_helper.rb
module SpotsHelper
end

app/views/admin/spots/edit.html.erb
<div class="container">
 <h6 class="text-center"><strong>スポット編集</strong></h6>
  <%= form_with model: @spot, url: admin_spot_path(@spot.id), method: :patch do |f| %>

  <div class="form-group">
   <%= f.label "スポット画像" %>
   <%= f.file_field :image, accept: "image/*" %>
  </div>

  <div class="form-group">
   <%= f.label "ジャンル名"%>
   <%= f.collection_select(:genre_id, Genre.all, :id, :genre_name) %>
  </div>

  <div class="form-group">
   <%= f.label "都道府県"%>
   <%= f.collection_select(:prefectures_id, Prefecture.all, :id, :prefecture_name) %>
  </div>

  <div class="form-group">
   <%= f.label "スポット名"%>
   <%= f.text_field :spot_name%>
  </div>

  <div class="form-group">
   <%= f.label "住所" %>
   <%= f.text_area :address, class: 'form-control' %>
  </div>

  <div class="form-group">
   <%= f.label "アクセス" %>
   <%= f.text_field :access, class: 'form-control' %>
  </div>

  <div class="form-group">
   <%= f.label "電話番号" %>
   <%= f.text_field :telephone_number, class: 'form-control' %>
  </div>

  <div class="form-group">
   <%= f.label "URL" %>
   <%= f.text_field :url, class: 'form-control' %>
  </div>

  <div class="form-group">
   <%= f.label "参考情報" %>
   <%= f.text_area :facility, class: 'form-control' %>
  </div>

  <div class="form-group">
   <%= f.label "営業時間" %>
   <%= f.text_area :business_day, class: 'form-control' %>
  </div>

  <div class="actions">
   <%= f.submit "変更を保存", class:"btn btn-success ms-3" %>
  </div>
  <% end %>
</div>

app/views/admin/spots/index.html.erb
<div class="container">
  <div class="row">
  <div class="col align-self-center">
    <%= search_form_for @q,url: admin_search_path do |f| %>

     <%= f.label :genre_id, 'ジャンル' %>
     <%= f.collection_select(:genre_id_eq, Genre.all, :id, :genre_name) %>

     <%= f.label :prefecture_id, '都道府県' %>
     <%= f.collection_select(:prefectures_id_eq, @prefectures, :id, :prefecture_name) %>
     <%= f.submit %>
    <% end %>
    </div>
  </div>

    <td>スポット一覧</td>
    <%=link_to '/admin/spots/new',method: :get do %>
    <i class="fa-solid fa-plus"></i>
    <% end %>
  <table class="table">
  <thead class="table-info">
    <tr>
      <th>スポット名</th>
      <th>住所</th>
    </tr>
  </thead>
  <tbody>
    <% @spots.each do |spot| %>
    <tr>
      <td><%= link_to spot.spot_name, admin_spot_path(spot) %></td>
      <td><%= spot.address %></td>
    </tr>
    <% end %>
  </tbody>
  </table>

<%= paginate @spots %>

</div>

app/views/admin/spots/new.html.erb
<div class="spot-new-container">
   <h6 class="text-center"><strong>新規スポット登録</strong></h6>
   
   <% if @spot.errors.any? %>
  <%= @spot.errors.count %>件のエラーが発生しました
  <ul>
    <% @spot.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>

   <%= form_with model: @spot, url: admin_spots_path,local:true do |f| %>

   <div class="form-group">
    <%= f.label "スポット画像" %>
    <%= f.file_field :image, accept: "image/*" %>
   </div>

   <div class="form-group">
    <%= f.label "ジャンル名"%>
    <%= f.collection_select(:genre_id, Genre.all, :id, :genre_name) %>
   </div>

   <div class="form-group">
    <%= f.label "都道府県"%>
    <%= f.collection_select(:prefectures_id, Prefecture.all, :id, :prefecture_name) %>
   </div>

   <div class="form-group">
    <%= f.label "スポット名"%>
    <%= f.text_field :spot_name%>
   </div>

   <div class="form-group">
    <%= f.label "住所" %>
    <%= f.text_area :address, class: 'form-control' %>
   </div>

   <div class="form-group">
    <%= f.label "アクセス" %>
    <%= f.text_field :access, class: 'form-control' %>
   </div>

   <div class="form-group">
    <%= f.label "電話番号" %>
    <%= f.text_field :telephone_number, class: 'form-control' %>
   </div>

   <div class="form-group">
    <%= f.label "URL" %>
    <%= f.text_field :url, class: 'form-control' %>
   </div>

   <div class="form-group">
    <%= f.label "参考情報" %>
    <%= f.text_area :facility, class: 'form-control' %>
   </div>


   <div class="form-group">
    <%= f.label "営業時間" %>
    <%= f.text_area :business_day, class: 'form-control' %>
   </div>


   <div class="actions">
    <%= f.submit "新規登録", class:"btn btn-success ms-3" %>
   </div>
   <% end %>
</div>

app/views/admin/spots/show.html.erb
<div class="spot-container">
  <div class ="row">
    <div class="col-md-4">
       <% if @spot.image.attached? %>
           <%= image_tag @spot.image, size: "400x400" %>
       <% else %>
           <%= image_tag '/assets/images/no_image.jpg', size: "400x400" %>
       <% end %>
    </div>
    <div class="col-md-8">
    <table>
     <tr>
      <td nowrap>【スポット名】</td>
      <td><%= @spot.spot_name %></td>
     </tr>
     <tr>
      <td nowrap>【都道府県】</td>
      <td><%= @spot.prefectures_id %></td>
     </tr>
     <tr>
      <td nowrap>【ジャンル】</th>
      <td><%= @spot.genre_id %></td>
     </tr>
     <tr>
      <td nowrap>【住所】</td>
      <td><%= @spot.address %></td>
     </tr>
     <tr>
      <td nowrap>【電話番号】</td>
      <td><%= @spot.telephone_number %></td>
     </tr>
     <tr>
      <td nowrap>【参考情報】</td>
      <td><%= @spot.facility %></td>
     </tr>
     <tr>
      <td nowrap>【URL】</td>
      <td><%= link_to @spot.url, "#{@spot.url}" %></td>
     </tr>
     <tr>
      <td nowrap>【アクセス】</td>
      <td><%= @spot.access %></td>
     </tr>
     <tr>
      <td nowrap>【営業時間】</td>
      <td><%= @spot.business_day %></td>
     </tr>
    </table>
       <%= link_to "編集する", edit_admin_spot_path, :class => "btn btn-success ms-3" %>
       <%= link_to "削除する", admin_spot_path, class:"btn btn btn-danger", method: :delete, "data-confirm" => "本当に削除しますか？" %>
    </div>
  </div>
</div>

app/views/spots/index.html.erb
<%= search_form_for @q do |f| %>

 <%= f.label :ジャンル %>
 <%= f.search_field :genre_name %>

 <%= f.label :prefecture_id %>
 <%= f.collection_select :prefecture_id_eq, @prefectures, :id, :name, include_blank: '指定なし' %>
 <%= f.submit %>
<% end %>