config/routes.rb
Rails.application.routes.draw do
  devise_for :customers, skip: [:passwords], controllers: {
   registrations: "public/registrations",
   sessions: "public/sessions"
  }

  devise_for :admin, skip: [:registrations, :passwords], controllers: {
   sessions: "admin/sessions"
  }
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html


  devise_scope :customer do
    post "customers/guest_sign_in", to: "public/sessions#guest_sign_in"
  end
  root to: "public/homes#top"


  scope module: :public do
    get "/customers/sign_up" => "registrations#new"
    post "/customers" => "registrations#create"
    get "/customers/mypage" => "customers#show"


    get "search", to: "spots#search"


    resources :spots, only: [:new, :create, :index, :show, :destroy] do
      resource :favorites, only: [:create, :destroy]
      resources :comments
    end
    resources :customers, only: [:show, :edit, :update] do
      get :favorites, on: :collection
    end
  end



  namespace :admin do
    get "search", to: "spots#search"
    get "/admin" => "homes#top"
    # delete '/spots/:id' => 'spots#destroy', as: 'destroy_spot'
    resources :spots
    resources :customers
    resources :genres
    resources :comments, only: :destroy
  end
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_one_attached :image
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :customer
  belongs_to :spot

  validates :rate, numericality: {
   less_than_or_equal_to: 5,
   greater_than_or_equal_to: 1,
 }, presence: true
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :spots, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :favorited_spots, through: :favorites, source: :spot
  has_many :comments, dependent: :destroy
  has_one_attached :image
  validates :name, presence: true
  validates :email, uniqueness: { message: "そのアドレスは使用できません" },
                  confirmation: true

  def self.guest
    find_or_create_by!(email: "guest@example.com") do |customer|
      customer.password = SecureRandom.urlsafe_base64
      customer.name = "ゲスト"
    end
  end

  def mine?(object)
    object.customer_id == id
  end

  def favorite(spot)
    favorites_spots << post
  end

  def unfavorite(spot)
    favorites_spots.destroy(post)
  end

  def favorite?(spot)
    favorites_spots.include?(post)
  end

  def get_image(width, height)
    unless image.attached?
      file_path = Rails.root.join("app/assets/images/no_image.jpg")
      image.attach(io: File.open(file_path), filename: "default-image.jpg", content_type: "image/jpeg")
    end
    image.variant(resize_to_limit: [width, height]).processed
  end
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :customer
  belongs_to :spot

  validates_uniqueness_of :spot_id, scope: :customer_id
end

app/models/genre.rb
class Genre < ApplicationRecord
  validates :genre_name, presence: true

  def self.ransackable_attributes(auth_object = nil)
    ["genre_name"]
  end
end

app/models/helpful.rb
class Helpful < ApplicationRecord
end

app/models/prefecture.rb
class Prefecture < ApplicationRecord
  validates :prefecture_name, presence: true, uniqueness: { case_sensitive: false }

  # belongs_to :spot
end

app/models/spot.rb
class Spot < ApplicationRecord
  has_one_attached :image
  belongs_to :customer, optional: true
  has_many :favorites, dependent: :destroy
  has_many :customers, through: :favorites
  has_many :comments, dependent: :destroy

  #  belongs_to :prefecture
  validates :spot_name, presence: true
  validates :address, presence: true
  validate :access
  validate :telephone_number
  validate :url
  validate :facility
  validate :business_day
  # validates :content, presence: true, length: { maximum: 65_535 }

  def get_image
    unless image.attached?
      file_path = Rails.root.join("app/assets/images/no_image.jpg")
      image.attach(io: File.open(file_path), filename: "default-image.jpg", content_type: "image/jpeg")
    end
    image
  end

  def self.ransackable_attributes(auth_object = nil)
    ["id", "genre_id", "prefectures_id"]
  end

  def self.ransackable_associations(auth_object = nil)
    ["genre", "prefecture"]
  end
end

app/models/user.rb
class User < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  def after_sign_out_path_for(resource_or_scope)
    if resource_or_scope == :customer
      root_path
    elsif resource_or_scope == :admin
      new_admin_session_path
    else
      admin_admin_path
    end
  end
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  before_action :set_spot
  before_action :authenticate_customer!
  
  def create
    if @spot.customer_id != current_customer.id
      @favorite = Favorite.create(customer_id: current_customer.id, spot_id: @spot.id)
    end
  end
  
  def destroy
    @favorite = Favorite.find_by(customer_id: current_customer.id, spot_id: @spot.id)
    @favorite.destroy
  end

  private
  def set_spot
    @spot = Spot.find(params[:spot_id])
  end
end

app/controllers/prefectures_controller.rb
class PrefecturesController < ApplicationController
  def index
    @q = Prefecture.ransack
    @prefectures = @q.result(distinct: true)
  end

  def search
    @q = Hoge.ransack(search_params)
    @prefectures = @q.result(distinct: true)
  end

  private
    def search_params
      params.require(:q).permit!
    end
end

app/helpers/admin/go_out_helper.rb
module Admin::GoOutHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/genres_helper.rb
module GenresHelper
end

app/helpers/prefectures_helper.rb
module PrefecturesHelper
end

app/helpers/spots_helper.rb
module SpotsHelper
end

app/views/admin/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation" data-turbo-cache="false">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/admin/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Lovepet</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>


    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://kit.fontawesome.com/08f25f8d84.js" crossorigin="anonymous"></script>
  </head>

  <body class="d-flex flex-column min-vh-100">
     <header>

      <nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top">
        <a class="navbar-brand" href="/">I♡PET</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav mr-auto">

          <% if customer_signed_in? %>

            <li class="nav-item">
              <%= link_to "マイページ", customers_mypage_path, class: 'btn btn-link' %>
            </li>
            <li class="nav-item">
              <%= link_to "お出かけスポット", spots_path, class: 'btn btn-link' %>
            </li>
            <li class="nav-item">
              <%= link_to "ログアウト", destroy_customer_session_path, method: :delete, class: 'btn btn-link' %>
            </li>
            <% elsif admin_signed_in? %>
            <li class="nav-item">
              <%= link_to "ログアウト", destroy_admin_session_path, method: :delete, class: 'btn btn-link' %>
            </li>
            <li class="nav-item">
              <%= link_to "管理者TOP", admin_admin_path, class: 'btn btn-link' %>
            </li>
            <% else %>
            <li class="nav-item">
              <a class="nav-link active" aria-current="page" href="/customers/sign_up">新規会員登録</a>
            </li>
            <li class="nav-item">
              <a class="nav-link active" aria-current="page" href="/customers/sign_in">ログイン</a>
            </li>
            <li class="nav-item">
              <%= link_to 'ゲストログイン', customers_guest_sign_in_path, class: "nav-link", method: :post  %>
            </li>
          <% end %>
          </ul>
        </div>
      </nav>
     </header>

    <div class="flex-grow-1">
      <%= yield %>
    </div>

     <footer class="bg-dark text-white pt-5 pb-4">
          <div class="d-flex">
              <div class="mx-auto">
                  <p class="footer-text">©2023 lovepet Inc.</p>
              </div>
          </div>
     </footer>
  </body>
</html>